[project]
name = "ref-lle"
version = "0.1.0"
description = "ReF-LLE: Personalized Low-Light Enhancement via Reference-Guided Deep RL"
readme = "README.md"
authors = [
    { name = "Anumeya", email = "sagely2005eagle@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "matplotlib",
    "notebook",
    "numpy",
    "pandas",
    "pillow",
    "pyiqa>=0.1.16",
    "pytest",
    "scikit-image",
    "torch",
    "torchvision",
    "tqdm",
]

[project.scripts]
ref-lle-train = "ref_lle.train:main"
ref-lle-infer = "ref_lle.infer:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"

[[tool.uv.index]]
name = "pytorch-cu124"
url = "https://download.pytorch.org/whl/cu124"
explicit = true

[tool.uv.sources]
torch = { index = "pytorch-cu124" }
torchvision = { index = "pytorch-cu124" }
